default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: apartments
  password: apartments

development:
  <<: *default
  database: apartments

production:
  <<: *default
  database: apartments

test:
  <<: *default
  database: apartments

staging:
  <<: *default
  database: apartments
